---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true  

- name: Create app directory
  file:
    path: "{{ app_path }}"
    state: directory
    owner: www-data
    group: www-data
  become: true

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx
  become: true

- name: Create site configuration
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    owner: www-data
    group: www-data
  become: true
  
