version: '3'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - db
    depends_on:
      - db

volumes:
  db-data: