---
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Create site configuration
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf